sudo: required
services:
  - docker

before_install:
  - docker build -t oisinf/fantasty_football_ui -f ff/Dockerfile.dev ff

script:
  - docker run -e CI=true oisinf/fantasty_football_ui npm run test
