sudo: required
services:
  - docker

before_install:
  - docker build -t oisinf/fantasy_football_ui -f ff/Dockerfile.dev ff

script:
  - docker run -e CI=true oisinf/fantasy_football_ui npm run test

deploy: 
  provider: heroku
  script: docker push registry.heroku.com/fantasy-football-u/web
  api_key:
    secure: $HEROKU_API_KEY