sudo: required
services:
  - docker

before_install:
  - docker build -t oisinf/fantasy_football_ui -f ff/Dockerfile.dev ff

script:
  - docker run -e CI=true oisinf/fantasy_football_ui npm run test
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy: 
  provider: script
  script: 
    docker push oisinf/fantasy_football_ui
  