services:
  - docker

before_install:
  - docker-compose build

script:
  #run tests
  - docker run -e CI=true CYPRESS_PROJECT_ID=$CYPRESS_PROJECT_ID CYPRESS_RECORD_KEY=$CYPRESS_RECORD_KEY oisinf/fantasy_football:prod npm run ui_tests
  #login in to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #install heroku cli
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  #login heroku registry
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
  #tag docker image as registry...
  - docker tag oisinf/fantasy_football:prod registry.heroku.com/$FANTASY_FOOTBALL_APP_NAME/web

deploy:
  provider: script
  #push tagged image to heroku registry
  #release
  script:
    docker push registry.heroku.com/$FANTASY_FOOTBALL_APP_NAME/web;
    heroku container:release web --app $FANTASY_FOOTBALL_APP_NAME;
  api_key:
    secure: $HEROKU_API_KEY
  on:
    branch: develop
